version: "3.8"

services:
  agent-api:
    build: .
    container_name: agent_api_service
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - DEBUG=True
    restart: always
